# Generated by Django 4.2.7 on 2023-11-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('comment', models.TextField()),
                ('view', models.IntegerField()),
                ('category', models.IntegerField()),
            ],
        ),
    ]
