# Generated by Django 4.2.7 on 2023-11-10 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='title',
            new_name='subject',
        ),
    ]
