# Generated by Django 4.2.7 on 2023-11-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.TextField(),
        ),
    ]
